## LOCAL

# DataSource
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DB?autoReconnect=true
    username: kws7802
    password: qwer!234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

